"""
Single-user login gate for the dashboard.

This app is meant for ONE person (you) to access privately, even though the
hosted URL itself may be technically reachable by anyone who has it. This
module blocks all access until the correct username/password is entered.

Credentials are never stored in code. Set them as secrets on your hosting
platform (Streamlit Community Cloud -> App settings -> Secrets, or your
host's environment-variable panel):

    AUTH_USERNAME = "yourname"
    AUTH_PASSWORD_HASH = "<sha256 hash, generated by generate_password_hash.py>"

Run `python generate_password_hash.py` locally to turn a real password into
the hash you paste into secrets -- your plaintext password is never sent to
Claude or stored anywhere in this repo.
"""

import hashlib
import hmac

import streamlit as st


def _hash(pw: str) -> str:
    return hashlib.sha256(pw.encode()).hexdigest()


def check_auth() -> bool:
    """Renders a login form if not authenticated. Returns True once logged in."""
    if st.session_state.get("authenticated"):
        return True

    st.title("🔐 Sign in")
    st.caption("This dashboard is private. Enter your credentials to continue.")

    expected_user = st.secrets.get("AUTH_USERNAME")
    expected_hash = st.secrets.get("AUTH_PASSWORD_HASH")

    if not expected_user or not expected_hash:
        st.error(
            "No login credentials configured yet. Set AUTH_USERNAME and "
            "AUTH_PASSWORD_HASH in your app's Secrets (see README.md -> "
            "Deployment for exact steps)."
        )
        return False

    with st.form("login_form"):
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")
        submitted = st.form_submit_button("Sign in", type="primary")

    if submitted:
        user_ok = hmac.compare_digest(username.strip(), expected_user)
        pass_ok = hmac.compare_digest(_hash(password), expected_hash)
        if user_ok and pass_ok:
            st.session_state.authenticated = True
            st.rerun()
        else:
            st.error("Incorrect username or password.")

    return False


def logout_button():
    if st.sidebar.button("🚪 Log out"):
        st.session_state.authenticated = False
        st.rerun()
