"""
Performance analytics for a completed backtest.
"""

import pandas as pd


def summarize(trades_df: pd.DataFrame, starting_capital: float) -> dict:
    if trades_df.empty:
        return {"total_trades": 0, "message": "No trades were generated by the strategy on this data."}

    wins = trades_df[trades_df["pnl"] > 0]
    losses = trades_df[trades_df["pnl"] <= 0]

    total_pnl = trades_df["pnl"].sum()
    equity = starting_capital + trades_df["pnl"].cumsum()
    running_max = equity.cummax()
    drawdown = equity - running_max
    max_drawdown = drawdown.min()

    return {
        "total_trades": len(trades_df),
        "wins": len(wins),
        "losses": len(losses),
        "win_rate_pct": round(100 * len(wins) / len(trades_df), 2),
        "gross_profit": round(wins["pnl"].sum(), 2),
        "gross_loss": round(losses["pnl"].sum(), 2),
        "net_pnl": round(total_pnl, 2),
        "net_return_pct": round(100 * total_pnl / starting_capital, 2),
        "avg_win": round(wins["pnl"].mean(), 2) if len(wins) else 0,
        "avg_loss": round(losses["pnl"].mean(), 2) if len(losses) else 0,
        "profit_factor": round(wins["pnl"].sum() / abs(losses["pnl"].sum()), 2) if losses["pnl"].sum() != 0 else float("inf"),
        "max_drawdown": round(max_drawdown, 2),
        "final_capital": round(starting_capital + total_pnl, 2),
    }


def print_summary(trades_df: pd.DataFrame, starting_capital: float):
    stats = summarize(trades_df, starting_capital)
    print("\n===== BACKTEST SUMMARY =====")
    for k, v in stats.items():
        label = k.replace("_", " ").title()
        print(f"{label:22}: {v}")
    print("=============================\n")
